from .ls import ls as ls
from .cd import cd as cd
from .cat import cat as cat
from .cp import cp as cp
from .mv import mv as mv
from .rm import rm as rm
from .zip import zip_cmd as zip_cmd
from .zip import unzip_cmd as unzip_cmd
from .tar import tar_cmd as tar_cmd
from .tar import untar_cmd as untar_cmd
from .grep import grep as grep
